name: Oracle Ampere Hunter

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, openssl, json

      - name: Install Project Dependencies
        run: composer install --no-dev

      - name: Create Temporary Key File
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > oracle_api_key.pem
          chmod 600 oracle_api_key.pem

      - name: Run OCI Instance Hunter
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_OCPUS: ${{ vars.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ vars.OCI_MEMORY_IN_GBS }}
          OCI_PRIVATE_KEY_FILE_PATH: oracle_api_key.pem
        run: php index.php
